# Generated by Django 3.2.7 on 2021-09-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='HW',
            fields=[
                ('hw_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hw_name', models.CharField(max_length=100)),
                ('hw_status', models.BooleanField()),
                ('hw_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hwcheck.course')),
            ],
            options={
                'verbose_name': 'ДЗ',
                'verbose_name_plural': 'ДЗ',
            },
        ),
    ]
