# Generated by Django 3.2.7 on 2021-09-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hw',
            name='hw_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
