# Generated by Django 3.2.7 on 2021-10-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwcheck', '0002_hw_hw_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw',
            name='hw_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
