# Generated by Django 3.2.7 on 2021-11-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwcheck', '0003_hw_hw_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw',
            name='HW_deadline',
            field=models.DateField(help_text='Date format mm/dd/yyyy', null=True),
        ),
    ]
