# Generated by Django 3.2.7 on 2021-10-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwcheck', '0004_auto_20211014_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw',
            name='hw_status',
            field=models.BooleanField(default=False),
        ),
    ]
