# Generated by Django 3.2.7 on 2022-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwcheck', '0004_alter_hw_hw_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw',
            name='HW_deadline',
            field=models.DateField(help_text='mm/dd/yyyy', null=True),
        ),
    ]
