# Generated by Django 3.2.7 on 2021-11-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hwcheck', '0005_alter_hw_hw_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hw',
            old_name='hw_course',
            new_name='HW_course',
        ),
        migrations.RenameField(
            model_name='hw',
            old_name='hw_id',
            new_name='HW_id',
        ),
        migrations.RenameField(
            model_name='hw',
            old_name='hw_info',
            new_name='HW_info',
        ),
        migrations.RenameField(
            model_name='hw',
            old_name='hw_name',
            new_name='HW_name',
        ),
        migrations.RenameField(
            model_name='hw',
            old_name='hw_status',
            new_name='HW_status',
        ),
    ]
